### ISSUE TITLE
open save failed

### ISSUE THREAD

**Issue by InnovationLou** [Nicolas-Constanty/WillowTreeBLDEnhanced#8] opened 2019-06-23 15:02 UTC
System.IO.FileFormatException: Input file is not a WSG (platform is Not WSG).
   在 WillowTree.WillowSaveGame.LoadWsg(String inputFile)
   在 WillowTree.WillowTreeMain.Open_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   在 System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   在 WillowTree.Program.Main()

**Comment by Nicolas-Constanty** [comment] 2019-06-24 08:16
Hello, can you please link the file that cause this error, i will look when i have some free time.

**Comment by 578777205** [comment] 2019-06-24 08:31
link success but when i open save file it throw FileFormatException,but i'm sure that save file can be loaded in game.
![image](https://user-images.githubusercontent.com/20527528/60003528-79dbf180-969d-11e9-8526-264bbbb2c9d5.png)

**Comment by Nicolas-Constanty** [comment] 2019-06-24 08:55
What i mean, is that it whould be easily for me to debug if i could test with your .sav file directly.

**Comment by 578777205** [comment] 2019-06-24 08:58
[Save0001.zip](https://github.com/Nicolas-Constanty/WillowTreeBLDEnhanced/files/3320030/Save0001.zip)

**Comment by Legit-Das** [comment] 2020-04-09 00:14
Same problem here.

**Comment by Nicolas-Constanty** [comment] 2020-04-09 19:43
> link success but when i open save file it throw FileFormatException,but i'm sure that save file can be loaded in game.
> ![image](https://user-images.githubusercontent.com/20527528/60003528-79dbf180-969d-11e9-8526-264bbbb2c9d5.png)

**Comment by Nicolas-Constanty** [comment] 2020-04-09 20:13
Hello @InnovationLou , 
When I try to open your save in my Borderland GOTY it doesn't work because the file is corrupt. 
I think we are using a different version of Borderland because your file is totally different from mine. If it's in chinese maybe that the version isn't the same than me.

@Legit-Das This error can be caused by many different things, it's actually difficult to know without the file causing the problem. Basically, this error means that the header of your save file isn't recognized.

**Comment by Legit-Das** [comment] 2020-04-10 05:31
@Nicolas-Constanty Thankfully [this version](https://sourceforge.net/projects/willowtree/files/2.3/) is working great for me. But here's my [SaveData folder](https://drive.google.com/open?id=17rH1jqKxAOmDZAKafLqo835FaraIqaeI) in case you wanted to check your version.

**Comment by Nicolas-Constanty** [comment] 2020-04-10 08:53
@Legit-Das Thanks for your feedback, this is fixed on last release.

**Closed as completed** 2020-04-19 02:25 UTC
